# Machine Learning - Numpy Tutorial

Steven Abreu - s.abreu@jacobs-university.de

In [57]:
import time

## Introduction

- What is NumPy?

Numpy is the most widely used Python package for scientific computing. It basically enables you to do everything in Python that you are used to doing in MATLAB. It is also the only numerical/computing library that we will allow you to use in this course. 

- What is vectorization?

Numpy offers *vectorized operations*, meaning operations that are optimized for executing your computations faster. It is faster than naive algorithms implemented using loops in Python. Here is a quick demonstration:

In [60]:
# Two 100x100 matrices in python
A_python = [[i for i in range(100)] for j in range(100)]
B_python = [[i for i in range(100)] for j in range(100)]
# Two 100x100 matrices in numpy
A_numpy = np.arange(10000).reshape(100,100)
B_numpy = np.arange(10000).reshape(100,100)

In [66]:
# naive python implementation
start = time.time()
C_python = [[0 for i in range(100)] for i in range(100)]
for i in range(100):
    for j in range(100):
        for k in range(100):
            C_python[i][j] = A_python[i][k] * B_python[k][j]
print('Time: {:6.5}s'.format(time.time() - start))

Time: 0.44675s


In [69]:
# vectorized matrix multiplication in numpy
start = time.time()
C_numpy = A_numpy @ B_numpy
print('Time: {:6.3}s'.format(time.time() - start))

Time: 0.00131s


As you can see, this is a huge difference! Thus, always use vectorized functions to do computations. 

## Download and Installation

Follow instructions at https://scipy.org/install.html

## Introductory Example

In this example, we will be computing

$$
Wx + b
$$

### Naive Python Implementation

In [75]:
# Inputs
W = [[4, 3, 2],
     [4, 3, 2],
     [4, 3, 2]]

x = [3, 9, 7]
b = [1, 1, 1]

# Output
y = [0, 0, 0]

# Naive Computation of Wx + b
for i in range(len(W)):
    for j in range(len(x)):
        y[i] += W[i][j] * x[j]

for i in range(len(y)):
    y[i] += b[i]

y

[54, 54, 54]

### NumPy-based Vectorized Implementation

In [76]:
import numpy as np

In [77]:
W = np.array([[4, 3, 2],
             [4, 3, 2],
             [4, 3, 2]])
W

array([[4, 3, 2],
       [4, 3, 2],
       [4, 3, 2]])

In [78]:
x = np.array([3, 9, 7])
x

array([3, 9, 7])

In [79]:
b = np.ones(3)
b

array([1., 1., 1.])

In [8]:
W.dot(x)
W @ x

array([20, 40, 60])

In [9]:
W.dot(x) + b

array([21., 41., 61.])

## Some other matrix examples

In [80]:
matrix = np.ones((500,500))
matrix

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [81]:
identity = np.eye(1000)
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

## Multi-Dimensional Arrays

In [85]:
T = np.random.random((2,2,4))
T

array([[[0.92058131, 0.57042211, 0.59159987, 0.09058767],
        [0.87707941, 0.16592986, 0.67579238, 0.60919437]],

       [[0.69351031, 0.59918124, 0.71290997, 0.27232504],
        [0.4777121 , 0.62656291, 0.89021992, 0.08342958]]])

In [86]:
W = T[1]
W, W.shape, W.dtype

(array([[0.69351031, 0.59918124, 0.71290997, 0.27232504],
        [0.4777121 , 0.62656291, 0.89021992, 0.08342958]]),
 (2, 4),
 dtype('float64'))

In [89]:
X = np.full((4,3), 2702)
X, X.shape, X.dtype

(array([[2702, 2702, 2702],
        [2702, 2702, 2702],
        [2702, 2702, 2702],
        [2702, 2702, 2702]]), (4, 3), dtype('int64'))

In [90]:
W.dot(X)

array([[6154.95756849, 6154.95756849, 6154.95756849],
       [5614.55202333, 5614.55202333, 5614.55202333]])

The function `array_equal` checks if two numpy arrays are equal (not element-wise).

In [92]:
X2 = np.zeros(X.shape)
np.array_equal(W.dot(X2), np.zeros((3,3)))

False

## Basic Element-wise Operations

In [93]:
y = np.arange(10)
y, np.array(range(10))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

This is an element-wise equality check for two numpy arrays

In [94]:
y == np.array(range(10))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [95]:
y + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
y * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
(y + 1)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [98]:
y + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
y / (y + 1)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [100]:
np.sqrt(y**2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [101]:
y.min(), y.max(), y.std(), y.sum()

(0, 9, 2.8722813232690143, 45)

## Indexing NumPy Arrays

In [107]:
T = np.arange(2 * 4 * 4).reshape(2, 4, 4)
T,  T.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]]), (2, 4, 4))

In [108]:
T[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
T[1,0,0]  # more efficient version of T[1][0][0]

16

You can also slice the matrix (i.e. take a "sub"-matrix from another matrix)

In [112]:
T[0,1:3,0:2]

array([[4, 5],
       [8, 9]])

Element wise comparison between matrix and scalar

In [113]:
(T % 10) == 0

array([[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [ True, False, False, False],
        [False, False, False, False],
        [False, False,  True, False]]])

You can index a matrix with a boolean matrix of the same dimensions (think of this like a filter function)

In [114]:
T[(T % 10) == 0]

array([ 0, 10, 20, 30])

In [115]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [116]:
x[x < 4]

array([1, 2, 3])

## Example: Masking and Clipping

In [117]:
W = np.random.randint(0, 10, (4, 4))
W

array([[8, 4, 7, 9],
       [2, 6, 3, 8],
       [8, 2, 8, 1],
       [0, 4, 9, 6]])

In [118]:
mask = np.ones_like(W)
mask[1] = 0
mask

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Masking is basically just element-wise multiplication with a binary matrix

In [120]:
W * mask

array([[8, 4, 7, 9],
       [0, 0, 0, 0],
       [8, 2, 8, 1],
       [0, 4, 9, 6]])

In [121]:
W > 5

array([[ True, False,  True,  True],
       [False,  True, False,  True],
       [ True, False,  True, False],
       [False, False,  True,  True]])

In [122]:
W2 = W
W2[W2 > 5] = 5
W2

array([[5, 4, 5, 5],
       [2, 5, 3, 5],
       [5, 2, 5, 1],
       [0, 4, 5, 5]])

You can clip the minimum or maximum value of a matrix

In [124]:
np.minimum(W, 5)

array([[5, 4, 5, 5],
       [2, 5, 3, 5],
       [5, 2, 5, 1],
       [0, 4, 5, 5]])

## Computation Along Axes

In [130]:
A = np.random.random((2,4))
A

array([[0.9363442 , 0.03432421, 0.5186222 , 0.80306425],
       [0.02420162, 0.92345741, 0.50867493, 0.85971851]])

You can compute the sum of a matrix along its different axes

In [131]:
A.sum()

4.608407331554301

In [132]:
A.sum(axis=0)

array([0.96054582, 0.95778162, 1.02729714, 1.66278276])

In [133]:
A.sum(axis=1)

array([2.29235486, 2.31605247])

Remember the argmax operator (it's everywhere in ML, check appendix B!)

In [135]:
A.max(axis=0), A.argmax(axis=0)

(array([0.9363442 , 0.92345741, 0.5186222 , 0.85971851]), array([0, 1, 0, 1]))

## Combining Arrays: Stacking & Concatenation

In [136]:
a = np.full(4, 1)
b = np.full(4, 2)
c = np.full(4, 3)
a, b, c

(array([1, 1, 1, 1]), array([2, 2, 2, 2]), array([3, 3, 3, 3]))

Stacking creates a new axis. It joins the supplied arrays, which must have the same shape, along that axis.
Indexing a single element from that axis returns the appropriate input array

In [137]:
B = np.stack([a, b, c], axis=1)
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (4, 3))

In [138]:
B[:,1]

array([2, 2, 2, 2])

Concatenating arrays joins them along an *existing* aixs.

In [139]:
C = np.concatenate([B+100, B+200], axis=1)
C

array([[101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203],
       [101, 102, 103, 201, 202, 203]])

## Transposing and Reshaping

In [140]:
B, B.shape

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), (4, 3))

In [141]:
BT = B.T
BT, BT.shape

(array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]), (3, 4))

Make sure that the dimensions are valid when you reshape and array!

In [144]:
BR = B.reshape(3, 4)
BR, BR.shape

(array([[1, 2, 3, 1],
        [2, 3, 1, 2],
        [3, 1, 2, 3]]), (3, 4))

## Broadcasting

In [146]:
A = np.random.random((8, 4))
B = np.random.random((4, 3))
A.dot(B).shape

(8, 3)

In [148]:
b = np.array([10, 20, 30])
b.shape

(3,)

In the following calculation, the array b (shape (3,)) is "broadcasted" into an array of shape (8,3) by repeating the same values in each row

Arrays must have same ending dimensions to broadcast.

In [151]:
A @ B + b

array([[11.02130726, 21.56692791, 31.5039578 ],
       [10.3176273 , 21.0070575 , 30.69648723],
       [10.91406745, 20.64519377, 30.98093792],
       [10.7645626 , 21.52508113, 31.13906836],
       [10.36729902, 21.09425414, 30.59266917],
       [10.47382007, 20.21230963, 30.30885788],
       [11.10817891, 20.98307235, 30.99947273],
       [10.98736847, 21.24276286, 31.08216416]])

Mismatched dimensions cause an error.

In [153]:
try:
  x = np.random.random((3,3,4))+np.random.random((3,2,4))
except ValueError as e:
  print(e)

operands could not be broadcast together with shapes (3,3,4) (3,2,4) 


## Saving and Loading

### Saving and loading a single NumPy array

In [154]:
# Save single array
x = np.random.random((5,))
print(x)

np.save('tmp.npy', x)

[0.83216186 0.82957944 0.29355734 0.26880541 0.51164854]


In [155]:
# Load the array
y = np.load('tmp.npy')

print(y)

[0.83216186 0.82957944 0.29355734 0.26880541 0.51164854]


### Saving and loading a dictionary of NumPy arrays

In [156]:
# Save dictionary of arrays
x1 = np.random.random((2,))
y1 = np.random.random((3,))
print(x1, y1)

np.savez('tmp.npz', x=x1, y=y1)

[0.01088308 0.10550936] [0.60105123 0.3800589  0.60249315]


In [157]:
# Load the dictionary of arrays
data = np.load('tmp.npz')

print(data['x'])
print(data['y'])

[0.01088308 0.10550936]
[0.60105123 0.3800589  0.60249315]


## References

You can find a more complete introduction at https://docs.scipy.org/doc/numpy/user/quickstart.html

The following links were helpful in preparing this notebook:

- https://docs.scipy.org/doc/numpy/reference/index.html
- CMU Deep Learning Course (Fall 2019)